# -*- coding: utf-8 -*-
"""LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIc_1d_yU-tCCCiDSPtGtGoB6FegmyL2
"""

### Transformers
from PIL import Image
from matplotlib import pyplot as plt
image=Image.open("/content/cat.1.jpg")
plt.imshow(image)

from transformers import pipeline
image_classifier=pipeline("image-classification")

image_classifier(image)

